"""empty message

Revision ID: 9fb79dc737c5
Revises: 
Create Date: 2017-04-01 01:19:20.693145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb79dc737c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('creator_facebook_id', sa.String(), nullable=False),
    sa.Column('target1_facebook_id', sa.String(), nullable=False),
    sa.Column('target2_facebook_id', sa.String(), nullable=False),
    sa.Column('matched_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
